name: Deploy to GitHub Pages

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for proper deployment

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Create .nojekyll file
        run: touch .nojekyll

      - name: Verify index.html exists
        run: |
          if [ ! -f "index.html" ]; then
            echo "Error: index.html not found in repository root!"
            exit 1
          else
            echo "index.html found in repository root"
            ls -la
          fi

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # The folder the action should deploy
          branch: gh-pages # The branch the action should deploy to
          clean: true # Automatically remove deleted files from the deploy branch
          clean-exclude: |
            .nojekyll
            CNAME
          commit-message: "Deploy waypoint-viewer to GitHub Pages"
          git-config-name: GitHub Actions
          git-config-email: actions@github.com
          single-commit: true
